### ISSUE TITLE
Division by 11 error

### ISSUE THREAD

**Issue by Joshuatolu** [rmotr-curriculum/free-python-course-questions#17]
I have tried to answer a question on verifying if a number is divisible by another number all to no avail. However, I think my code is correct, so I do not know what is wrong. Below is my code:

divisible_by_11 = 11
is_911_divisible_by_11 = None

number_911 = 911

if [number_911%divisible_by_11==0]:

    is_911_divisible_by_11 = True

else:

    is_911_divisible_by_11 = False

Kindly point out my error. Thanks.

**Comment by jawsino** [comment]
How about putting the "==0" after the bracket? Remember, you are testing the statement against 0 so it should be outside the brackets. Order of operations applies as well.

**Comment by Joshuatolu** [comment]
Thanks, @jawsino, removing the square brackets altogether solved the problem.
