### ISSUE TITLE
Why does the message_2 show as undefined?

### ISSUE THREAD

**Issue by webtech-pmp** [rmotr-curriculum/free-python-course-questions#42]
When I try with only message_1 it works but when I try with message_2 there is an error. How does message_2 need to be defined?

**Assignment**: http://learn.rmotr.com/python/free-python-course/getting-started/the-equals-operator

**User code**:
```python
x = 10

# Remove square brackets and complete if statement conditions to make code run
if x == 10:
    message_1 = "Hello World"

if x != 10:
    message_2 = "This is RMOTR"


print(message_1)
print(message_2)
```

**Comment by santiagobasulto** [comment]
`x` is 10. It's impossible to evaluate `x != 10`. You should try other condition. "A fruit can't be an apple and an orange at the same time" we always say. If x is 10, it isn't anything else.
